name: modik_pages
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  http: ^1.6.0
  sqflite: ^2.4.2+1
  path: ^1.9.1
  font_awesome_flutter: ^10.7.0

  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2   # ✅ مهم جداً لإصلاح اللغة

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/modrik.jpg
    - assets/header_pattern.png
    - assets/dnacolor.png
    - assets/vcf-file.png
    - assets/chat_bot.png
    - assets/expert.png
    - assets/security.png