// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu20dS4u2lwFhGukgLDMA8noDtEFYEaeE',
    appId: '1:954028606901:web:0fec35913785ba8222c5fc',
    messagingSenderId: '954028606901',
    projectId: 'modrik-1f0d3',
    authDomain: 'modrik-1f0d3.firebaseapp.com',
    storageBucket: 'modrik-1f0d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7yUPRK46T0Qzg2AbhZC4rNz8e7fkS1xk',
    appId: '1:954028606901:android:5fae096283b340a222c5fc',
    messagingSenderId: '954028606901',
    projectId: 'modrik-1f0d3',
    storageBucket: 'modrik-1f0d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVx7arJfQtG60RiRjwPpoJEBj_I2MQzLI',
    appId: '1:954028606901:ios:066266636efcd7dc22c5fc',
    messagingSenderId: '954028606901',
    projectId: 'modrik-1f0d3',
    storageBucket: 'modrik-1f0d3.firebasestorage.app',
    iosBundleId: 'com.example.modikPages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVx7arJfQtG60RiRjwPpoJEBj_I2MQzLI',
    appId: '1:954028606901:ios:066266636efcd7dc22c5fc',
    messagingSenderId: '954028606901',
    projectId: 'modrik-1f0d3',
    storageBucket: 'modrik-1f0d3.firebasestorage.app',
    iosBundleId: 'com.example.modikPages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfAyWF2UHG_C5RDxHCwpuII4ZF4r6BgwY',
    appId: '1:954028606901:web:8b560b1734ac5b0222c5fc',
    messagingSenderId: '954028606901',
    projectId: 'modrik-1f0d3',
    authDomain: 'modrik-1f0d3.firebaseapp.com',
    storageBucket: 'modrik-1f0d3.firebasestorage.app',
  );
}
